# Generated by Django 5.0.9 on 2026-09-24 05:50

import apps.core.money
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=10)),
                ('round_count', models.PositiveSmallIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_negotiations', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_negotiations', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='marketplace.job')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation', to='proposals.proposal')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('amount', apps.core.money.MoneyField()),
                ('deadline', models.DateTimeField()),
                ('deliverables', models.TextField(max_length=3000)),
                ('revision_limit', models.PositiveSmallIntegerField(default=2)),
                ('requirements', models.TextField(blank=True, max_length=3000)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('ACTIVE', 'Awaiting response'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COUNTERED', 'Countered'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='ACTIVE', max_length=10)),
                ('is_final', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True, max_length=1000)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='negotiations.negotiation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to=settings.AUTH_USER_MODEL)),
                ('replies_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='negotiations.offer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('round_number', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='negotiation',
            name='current_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_current_for', to='negotiations.offer'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['negotiation', 'round_number'], name='negotiation_negotia_1916b2_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['receiver', 'status'], name='negotiation_receive_26fbc5_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'expires_at'], name='negotiation_status_e8769e_idx'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='offer_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='negotiation',
            index=models.Index(fields=['client', 'status'], name='negotiation_client__2bb001_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiation',
            index=models.Index(fields=['freelancer', 'status'], name='negotiation_freelan_b3316f_idx'),
        ),
    ]
