# Generated by Django 5.0.9 on 2026-09-24 05:50

import apps.core.money
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon key used by the templates.', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='profiles.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/freelancer/%Y/%m/')),
                ('professional_title', models.CharField(blank=True, max_length=160)),
                ('bio', models.TextField(blank=True, max_length=3000)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('website', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('hourly_rate', apps.core.money.MoneyField(help_text='Indicative rate in SkillCoin per hour.')),
                ('availability', models.CharField(choices=[('FULL_TIME', 'Available full time'), ('PART_TIME', 'Available part time'), ('LIMITED', 'Limited availability'), ('UNAVAILABLE', 'Not available')], db_index=True, default='FULL_TIME', max_length=12)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry level'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], db_index=True, default='INTERMEDIATE', max_length=12)),
                ('years_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('completed_projects', models.PositiveIntegerField(db_index=True, default=0)),
                ('active_projects', models.PositiveIntegerField(default=0)),
                ('total_earned', apps.core.money.MoneyField()),
                ('proposals_submitted', models.PositiveIntegerField(default=0)),
                ('proposals_accepted', models.PositiveIntegerField(default=0)),
                ('on_time_deliveries', models.PositiveIntegerField(default=0)),
                ('late_deliveries', models.PositiveIntegerField(default=0)),
                ('is_profile_complete', models.BooleanField(db_index=True, default=False)),
                ('is_available_for_hire', models.BooleanField(db_index=True, default=True)),
                ('search_text', models.TextField(blank=True, db_index=True, editable=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='freelancers', to='profiles.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=160)),
                ('company', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('employment_type', models.CharField(blank=True, max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.freelancerprofile')),
            ],
            options={
                'ordering': ('-is_current', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=180)),
                ('degree', models.CharField(max_length=160)),
                ('field', models.CharField(blank=True, max_length=160, verbose_name='field of study')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.freelancerprofile')),
            ],
            options={
                'verbose_name_plural': 'education',
                'ordering': ('-end_date', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('usage_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='profiles.category')),
            ],
            options={
                'ordering': ('-usage_count', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FreelancerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=2)),
                ('years', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('is_primary', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to='profiles.freelancerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_entries', to='profiles.skill')),
            ],
            options={
                'ordering': ('-is_primary', '-level', 'skill__name'),
            },
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancers', through='profiles.FreelancerSkill', to='profiles.skill'),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/client/%Y/%m/')),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('company_description', models.TextField(blank=True, max_length=2000)),
                ('company_size', models.CharField(blank=True, max_length=40)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('website', models.URLField(blank=True)),
                ('jobs_posted', models.PositiveIntegerField(default=0)),
                ('active_projects', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('total_hired', models.PositiveIntegerField(default=0)),
                ('total_spent', apps.core.money.MoneyField()),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('search_text', models.TextField(blank=True, db_index=True, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['search_text'], name='clientprofile_search_text')],
            },
        ),
        migrations.AddConstraint(
            model_name='freelancerskill',
            constraint=models.UniqueConstraint(fields=('profile', 'skill'), name='freelancerskill_unique'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['search_text'], name='freelancerprofile_search_text'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['availability', 'is_available_for_hire'], name='profiles_fr_availab_fb7449_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['-completed_projects'], name='profiles_fr_complet_acba0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='freelancerprofile',
            constraint=models.CheckConstraint(check=models.Q(('hourly_rate__gte', Decimal('0.00'))), name='freelancer_rate_non_negative'),
        ),
    ]
