# Generated by Django 5.2.17 on 2026-09-25 21:56

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(db_index=True, default=apps.accounts.models._otp_code, max_length=6),
        ),
    ]
