# Generated by Django 5.2.17 on 2026-09-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
        ('wallets', '0003_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='client_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_agreements', to='wallets.wallettransaction'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='work_submission',
            field=models.TextField(blank=True),
        ),
    ]
