# Generated by Django 5.2.17 on 2026-09-26 16:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreement_client_feedback_agreement_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='submission_file',
            field=models.FileField(blank=True, help_text='Proof of work, screenshot, deliverables archive or document', null=True, upload_to='agreements/submissions/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='submission_link',
            field=models.URLField(blank=True, help_text='Google Drive, Dropbox, GitHub, Figma, or live demo link', max_length=500),
        ),
        migrations.CreateModel(
            name='AgreementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to='agreements/attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='agreements.agreement')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
