# Generated by Django 5.0.9 on 2026-09-24 05:50

import apps.core.money
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='jobs/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=60)),
                ('day', models.DateField(default=django.utils.timezone.localdate)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=240)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('budget', apps.core.money.MoneyField(help_text='Committed budget; reserved on publish.')),
                ('job_type', models.CharField(choices=[('FIXED', 'Fixed price'), ('HOURLY', 'Hourly'), ('MILESTONE', 'Milestone based')], default='FIXED', max_length=10)),
                ('complexity', models.CharField(choices=[('SIMPLE', 'Simple'), ('INTERMEDIATE', 'Intermediate'), ('COMPLEX', 'Complex'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=12)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry level'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=12)),
                ('deadline', models.DateTimeField()),
                ('estimated_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('people_required', models.PositiveSmallIntegerField(default=1, help_text='How many freelancers the work needs.')),
                ('team_required', models.BooleanField(default=False, help_text='The hired freelancer is expected to build a team.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PROPOSAL_RECEIVED', 'Proposals received'), ('NEGOTIATING', 'Negotiating'), ('HIRED', 'Freelancer hired'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=18)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('visibility_note', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('budget_reserved_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_amount', apps.core.money.MoneyField(help_text='Currently held in reserve for this job.')),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proposal_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('moderation_note', models.CharField(blank=True, max_length=300)),
                ('search_text', models.TextField(blank=True, db_index=True, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='profiles.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('hired_freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
