# Generated by Django 5.0.9 on 2026-09-24 05:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('profiles', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='reserve_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_jobs', to='wallets.wallettransaction'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='jobattachment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketplace.job'),
        ),
        migrations.AddField(
            model_name='jobattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='marketplace.job'),
        ),
        migrations.AddField(
            model_name='jobview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='marketplace.job'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-published_at'], name='marketplace_status_87a137_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['client', '-created_at'], name='marketplace_client__7ebe3a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', 'status'], name='marketplace_categor_f33c47_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-budget'], name='marketplace_budget_29e6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['deadline'], name='marketplace_deadlin_60422f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['search_text'], name='job_search_text'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(('budget__gt', Decimal('0.00'))), name='job_budget_positive'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(('people_required__gte', 1)), name='job_people_required_min'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ['OPEN', 'PROPOSAL_RECEIVED', 'NEGOTIATING']), _negated=True), ('budget_reserved_at__isnull', False), _connector='OR'), name='job_open_requires_reservation'),
        ),
        migrations.AddConstraint(
            model_name='jobview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('job', 'user', 'day'), name='jobview_unique_user_day'),
        ),
        migrations.AddConstraint(
            model_name='jobview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('job', 'session_key', 'day'), name='jobview_unique_session_day'),
        ),
        migrations.AddConstraint(
            model_name='savedjob',
            constraint=models.UniqueConstraint(fields=('job', 'user'), name='savedjob_unique'),
        ),
    ]
