# Generated by Django 5.2.17 on 2026-09-26 11:31

import apps.core.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='proposal',
            new_name='proposals_p_job_id_42265a_idx',
            old_name='proposals_p_job_id_244837_idx',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='proposals_p_freelan_3c8625_idx',
            old_name='proposals_p_freelan_41935c_idx',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='proposals_p_status_20826d_idx',
            old_name='proposals_p_status_ee132f_idx',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposed_amount',
            field=apps.core.money.MoneyField(help_text='Proposed budget in SkillCoin.'),
        ),
    ]
