# Generated by Django 5.0.9 on 2026-09-24 05:50

import apps.core.money
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', apps.core.money.MoneyField()),
                ('status', models.CharField(choices=[('ALLOCATED', 'Allocated'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='ALLOCATED', max_length=10)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('trigger', models.CharField(blank=True, choices=[('CLIENT_APPROVAL', 'Client approved'), ('AUTO_RELEASE', '48-hour rule'), ('PROJECT_APPROVAL', 'Final project approval'), ('DISPUTE_RESOLUTION', 'Dispute resolution'), ('ADMIN_RELEASE', 'Administrator release')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('funded_amount', apps.core.money.MoneyField(help_text='Total ever placed in escrow for this project.')),
                ('held_amount', apps.core.money.MoneyField(help_text='Still locked.')),
                ('released_amount', apps.core.money.MoneyField(help_text='Paid out to freelancers.')),
                ('refunded_amount', apps.core.money.MoneyField(help_text='Returned to the client.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIALLY_RELEASED', 'Partially released'), ('RELEASED', 'Released'), ('DISPUTED', 'Disputed'), ('REFUNDED', 'Refunded')], db_index=True, default='ACTIVE', max_length=20)),
                ('funded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='An open dispute freezes every movement.')),
                ('lock_reason', models.CharField(blank=True, max_length=300)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrows', to='agreements.agreement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
