# Generated by Django 5.0.9 on 2026-09-24 05:50

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='hold_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_holds', to='wallets.wallettransaction'),
        ),
        migrations.AddField(
            model_name='escrow',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow', to='projects.project'),
        ),
        migrations.AddField(
            model_name='escrowallocation',
            name='credit_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_credits', to='wallets.wallettransaction'),
        ),
        migrations.AddField(
            model_name='escrowallocation',
            name='debit_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_debits', to='wallets.wallettransaction'),
        ),
        migrations.AddField(
            model_name='escrowallocation',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='escrow.escrow'),
        ),
        migrations.AddField(
            model_name='escrowallocation',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowallocation',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowallocation',
            name='task',
            field=models.OneToOneField(blank=True, help_text='Null for the final, non-task payment of any remainder.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_record', to='tasks.task'),
        ),
        migrations.AddConstraint(
            model_name='escrow',
            constraint=models.CheckConstraint(check=models.Q(('held_amount__gte', Decimal('0.00'))), name='escrow_held_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='escrow',
            constraint=models.CheckConstraint(check=models.Q(('funded_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('held_amount'), '+', models.F('released_amount')), '+', models.F('refunded_amount')))), name='escrow_balances_reconcile'),
        ),
        migrations.AddIndex(
            model_name='escrowallocation',
            index=models.Index(fields=['escrow', '-created_at'], name='escrow_escr_escrow__14fae0_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowallocation',
            index=models.Index(fields=['status', '-released_at'], name='escrow_escr_status_7eac1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='escrowallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='escrowallocation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit_transaction__isnull', False), ('status', 'RELEASED')), models.Q(('status', 'RELEASED'), _negated=True), _connector='OR'), name='allocation_released_requires_transaction'),
        ),
    ]
