# Generated by Django 5.0.9 on 2026-09-24 05:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('HERO', 'Hero'), ('CLIENT_VALUE', 'For clients'), ('FREELANCER_VALUE', 'For freelancers'), ('HOW_IT_WORKS', 'How it works'), ('TRUST', 'Trust and safety'), ('CTA', 'Closing call to action')], db_index=True, max_length=24)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('button_text', models.CharField(blank=True, max_length=60)),
                ('button_url', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('slot', 'sort_order'),
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('value', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('TEXT', 'Long text')], default='STRING', max_length=10)),
                ('group', models.CharField(db_index=True, default='general', max_length=60)),
                ('label', models.CharField(max_length=160)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('is_public', models.BooleanField(default=False, help_text='Readable from templates without signing in.')),
            ],
            options={
                'ordering': ('group', 'key'),
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('JOB_CREATED', 'Job created'), ('JOB_PUBLISHED', 'Job published'), ('JOB_CANCELLED', 'Job cancelled'), ('BUDGET_RESERVED', 'Budget reserved'), ('BUDGET_RELEASED', 'Budget released'), ('PROPOSAL_SUBMITTED', 'Proposal submitted'), ('PROPOSAL_WITHDRAWN', 'Proposal withdrawn'), ('PROPOSAL_REJECTED', 'Proposal rejected'), ('NEGOTIATION_OPENED', 'Negotiation opened'), ('OFFER_CREATED', 'Offer created'), ('COUNTER_OFFER', 'Counter offer'), ('OFFER_ACCEPTED', 'Offer accepted'), ('OFFER_REJECTED', 'Offer rejected'), ('AGREEMENT_ACCEPTED', 'Agreement accepted'), ('AGREEMENT_MODIFIED', 'Agreement modified'), ('DEADLINE_EXTENDED', 'Deadline extended'), ('DEPOSIT_SUBMITTED', 'Deposit submitted'), ('DEPOSIT_APPROVED', 'Deposit approved'), ('DEPOSIT_REJECTED', 'Deposit rejected'), ('ESCROW_FUNDED', 'Escrow funded'), ('ALLOCATION_SET', 'Task allocation set'), ('PAYMENT_RELEASED', 'Payment released'), ('PAYMENT_AUTO_RELEASED', 'Payment auto-released'), ('REFUND_ISSUED', 'Refund issued'), ('WITHDRAWAL_REQUESTED', 'Withdrawal requested'), ('WITHDRAWAL_COMPLETED', 'Withdrawal completed'), ('WITHDRAWAL_REJECTED', 'Withdrawal rejected'), ('PROJECT_CREATED', 'Project created'), ('PROJECT_READY_FOR_REVIEW', 'Project ready for review'), ('PROJECT_COMPLETED', 'Project completed'), ('PROJECT_CANCELLED', 'Project cancelled'), ('TEAM_CREATED', 'Team created'), ('MEMBER_INVITED', 'Member invited'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('INVITATION_DECLINED', 'Invitation declined'), ('MEMBER_REMOVED', 'Member removed'), ('TASK_CREATED', 'Task created'), ('TASK_ASSIGNED', 'Task assigned'), ('TASK_STARTED', 'Task started'), ('WORK_SUBMITTED', 'Work submitted'), ('REVISION_REQUESTED', 'Revision requested'), ('TASK_APPROVED', 'Task approved'), ('FILE_UPLOADED', 'File uploaded'), ('MESSAGE_SENT', 'Message sent'), ('CONVERSATION_ARCHIVED', 'Conversation archived'), ('REVIEW_SUBMITTED', 'Review submitted'), ('DISPUTE_CREATED', 'Dispute created'), ('DISPUTE_RESOLVED', 'Dispute resolved')], db_index=True, max_length=40)),
                ('description', models.CharField(max_length=400)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('target_url', models.CharField(blank=True, max_length=400)),
                ('visibility', models.CharField(choices=[('PARTICIPANTS', 'Project participants'), ('PUBLIC', 'Anyone'), ('ADMIN', 'Administrators only')], default='PARTICIPANTS', max_length=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
