# Generated by Django 5.0.9 on 2026-09-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='job_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='project_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
