# Generated by Django 5.0.9 on 2026-09-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='task_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['project_id', '-created_at'], name='core_activi_project_a13552_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['job_id', '-created_at'], name='core_activi_job_id_247b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor', '-created_at'], name='core_activi_actor_i_144aa7_idx'),
        ),
    ]
