# Generated by Django 5.0.9 on 2026-09-24 05:50

import apps.core.money
import apps.wallets.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_balance', apps.core.money.MoneyField(help_text='Spendable SkillCoin.')),
                ('reserved_balance', apps.core.money.MoneyField(help_text='Locked for published job budgets or a pending withdrawal.')),
                ('escrow_balance', apps.core.money.MoneyField(help_text='Committed to funded projects.')),
                ('lifetime_deposited', apps.core.money.MoneyField()),
                ('lifetime_withdrawn', apps.core.money.MoneyField()),
                ('lifetime_earned', apps.core.money.MoneyField()),
                ('lifetime_spent', apps.core.money.MoneyField()),
                ('is_frozen', models.BooleanField(default=False, help_text='Admin freeze — blocks every outgoing movement.')),
                ('frozen_reason', models.CharField(blank=True, max_length=300)),
                ('version', models.PositiveBigIntegerField(default=0, help_text='Incremented on every mutation; detects lost updates.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('internal_transaction_id', models.CharField(db_index=True, default=apps.wallets.models._internal_txn_id, editable=False, max_length=32, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('BUDGET_RESERVATION', 'Job budget reserved'), ('BUDGET_RELEASE', 'Job budget released'), ('ESCROW_HOLD', 'Escrow hold'), ('ESCROW_RELEASE', 'Escrow released'), ('PROJECT_PAYMENT', 'Project payment'), ('REFUND', 'Refund'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_REVERSAL', 'Withdrawal reversal'), ('ADJUSTMENT', 'Administrative adjustment')], db_index=True, max_length=22)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], db_index=True, default='COMPLETED', max_length=10)),
                ('amount', apps.core.money.MoneyField(help_text='Always positive; direction is implied by from/to bucket.')),
                ('delta', apps.core.money.SignedMoneyField(help_text='Signed effect on the wallet total (0 for internal bucket moves).')),
                ('from_bucket', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ESCROW', 'Escrow'), ('EXTERNAL', 'External')], max_length=10)),
                ('to_bucket', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ESCROW', 'Escrow'), ('EXTERNAL', 'External')], max_length=10)),
                ('balance_before', apps.core.money.MoneyField(help_text='Wallet total before this row.')),
                ('balance_after', apps.core.money.MoneyField(help_text='Wallet total after this row.')),
                ('available_after', apps.core.money.MoneyField()),
                ('reserved_after', apps.core.money.MoneyField()),
                ('escrow_after', apps.core.money.MoneyField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, help_text='Admin or user who triggered this row; null for scheduled jobs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_transactions', to=settings.AUTH_USER_MODEL)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_transactions', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.PositiveIntegerField(blank=True, null=True)),
                ('project_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked', to='wallets.wallettransaction')),
                ('task_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('available_balance__gte', Decimal('0.00'))), name='wallet_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('reserved_balance__gte', Decimal('0.00'))), name='wallet_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('escrow_balance__gte', Decimal('0.00'))), name='wallet_escrow_non_negative'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', '-created_at'], name='wallets_wal_user_id_a917f9_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='wallets_wal_transac_ab2e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['project_id', '-created_at'], name='wallets_wal_project_7d53cd_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status', 'transaction_type'], name='wallets_wal_status_e3b962_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['internal_transaction_id'], name='wallets_wal_interna_b98e4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='ledger_amount_positive'),
        ),
    ]
