# Generated by Django 5.2.17 on 2026-09-25 22:17

import apps.core.money
import apps.wallets.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference_id', models.CharField(db_index=True, default=apps.wallets.models._deposit_ref, editable=False, max_length=32, unique=True)),
                ('amount', apps.core.money.MoneyField(help_text='Amount in BDT / SkillCoin.')),
                ('payment_method', models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('BANK', 'Bank Transfer'), ('TEST', 'Instant Sandbox / Test Deposit')], default='BKASH', max_length=10)),
                ('sender_number', models.CharField(blank=True, help_text='Mobile or account number used to send money.', max_length=30)),
                ('transaction_id', models.CharField(blank=True, help_text="Provider's transaction ID (e.g. bKash TrxID).", max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=12)),
                ('admin_note', models.CharField(blank=True, max_length=300)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deposits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallets_dep_user_id_ece5bb_idx'), models.Index(fields=['status', '-created_at'], name='wallets_dep_status_7aebd8_idx')],
            },
        ),
    ]
