# Generated by Django 5.2.17 on 2026-09-25 22:46

import apps.core.money
import apps.wallets.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_deposit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference_id', models.CharField(db_index=True, default=apps.wallets.models._withdrawal_ref, editable=False, max_length=32, unique=True)),
                ('amount', apps.core.money.MoneyField(help_text='Amount in SkillCoin / BDT.')),
                ('payment_method', models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('BANK', 'Bank Transfer')], default='BKASH', max_length=10)),
                ('account_number', models.CharField(help_text='Mobile banking number or Bank account details.', max_length=50)),
                ('account_name', models.CharField(blank=True, help_text='Account holder name.', max_length=100)),
                ('external_transaction_id', models.CharField(blank=True, help_text='Transaction ID / reference from provider.', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved & Paid'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=12)),
                ('admin_note', models.CharField(blank=True, max_length=300)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallets_wit_user_id_cda309_idx'), models.Index(fields=['status', '-created_at'], name='wallets_wit_status_f33015_idx')],
            },
        ),
    ]
