# Generated by Django 5.0.9 on 2026-09-24 05:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=240)),
                ('description', models.TextField(max_length=5000)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='portfolio/covers/%Y/%m/')),
                ('demo_url', models.URLField(blank=True, help_text='Live demo, if there is one.')),
                ('repository_url', models.URLField(blank=True, help_text='Source code, where it can be shared.')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated technology list.', max_length=400)),
                ('tech_stack', models.CharField(blank=True, max_length=400)),
                ('role', models.CharField(blank=True, help_text="The freelancer's role.", max_length=160)),
                ('responsibilities', models.TextField(blank=True, max_length=2000)),
                ('outcome', models.TextField(blank=True, help_text='Result achieved.', max_length=2000)),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, help_text='Leave blank if under NDA.', max_length=160)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('confidentiality_note', models.CharField(blank=True, help_text='Shown instead of client details when work is under NDA.', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('search_text', models.TextField(blank=True, db_index=True, editable=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_entries', to='profiles.category')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='profiles.freelancerprofile')),
                ('skills', models.ManyToManyField(blank=True, related_name='portfolio_entries', to='profiles.skill')),
                ('source_project_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order', '-completed_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='portfolio/media/%Y/%m/')),
                ('kind', models.CharField(choices=[('SCREENSHOT', 'Screenshot'), ('IMAGE', 'Image'), ('DIAGRAM', 'Diagram')], default='SCREENSHOT', max_length=12)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name_plural': 'portfolio media',
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=60)),
                ('viewed_on', models.DateField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='portfolios.portfolio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['search_text'], name='portfolio_search_text'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['freelancer', 'is_public', 'order'], name='portfolios__freelan_dae285_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolioview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('portfolio', 'user', 'viewed_on'), name='portfolioview_unique_user_day'),
        ),
        migrations.AddConstraint(
            model_name='portfolioview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('portfolio', 'session_key', 'viewed_on'), name='portfolioview_unique_session_day'),
        ),
    ]
