# Generated by Django 5.0.9 on 2026-09-24 05:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_proposals', models.BooleanField(default=True)),
                ('email_tasks', models.BooleanField(default=True)),
                ('email_deadlines', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('NEW_PROPOSAL', 'New proposal'), ('PROPOSAL_ACCEPTED', 'Proposal accepted'), ('PROPOSAL_REJECTED', 'Proposal rejected'), ('NEW_MESSAGE', 'New message'), ('MENTION', 'You were mentioned'), ('NEW_OFFER', 'New offer'), ('COUNTER_OFFER', 'Counter offer'), ('OFFER_EXPIRED', 'Offer expired'), ('AGREEMENT_ACCEPTED', 'Agreement accepted'), ('AGREEMENT_MODIFICATION', 'Agreement modification request'), ('TEAM_INVITATION', 'Team invitation'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('INVITATION_DECLINED', 'Invitation declined'), ('TASK_ASSIGNED', 'Task assigned'), ('WORK_SUBMITTED', 'Work submitted'), ('REVISION_REQUESTED', 'Revision requested'), ('TASK_APPROVED', 'Task approved'), ('DEPOSIT_APPROVED', 'Deposit approved'), ('DEPOSIT_REJECTED', 'Deposit rejected'), ('ESCROW_FUNDED', 'Escrow funded'), ('PAYMENT_RELEASED', 'Payment released'), ('PAYMENT_WINDOW_OPENED', 'Review window opened'), ('PAYMENT_WINDOW_CLOSING', 'Review window closing'), ('WITHDRAWAL_UPDATE', 'Withdrawal update'), ('REVIEW_RECEIVED', 'Review received'), ('DISPUTE_CREATED', 'Dispute created'), ('DISPUTE_RESOLVED', 'Dispute resolved'), ('DEADLINE_APPROACHING', 'Deadline approaching'), ('PROJECT_READY_FOR_REVIEW', 'Project ready for review'), ('PROJECT_COMPLETED', 'Project completed'), ('JOB_CANCELLED', 'Job cancelled'), ('ACCOUNT_NOTICE', 'Account notice')], db_index=True, max_length=32)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=8)),
                ('title', models.CharField(max_length=180)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx'), models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_028906_idx')],
            },
        ),
    ]
